/**
 * Chimpanzee Layer — Exported tools for syncing backups.
 * (This complements the interaction tracking in chimpanzee.ts)
 */

export const BACKUP_SYNC_TOOLS = [
  {
    name: "memory_backup_upload",
    description:
      "Upload a local Aegis memory snapshot backup to a remote cloud storage location (like Google Drive). This preserves memory safely off-device.",
    parameters: {
      type: "object",
      properties: {
        localBackupPath: {
          type: "string",
          description: "Absolute path to the local .db.bak or .jsonl file generated by memory_backup tool.",
        },
        cloudDestinationPath: {
          type: "string",
          description: "Logical directory or folder ID on the remote cloud where the file should be saved.",
        },
      },
      required: ["localBackupPath", "cloudDestinationPath"],
    },
  },
  {
    name: "memory_backup_download",
    description:
      "Download a remote memory snapshot backup from a cloud storage location into a local temporary file for restoration.",
    parameters: {
      type: "object",
      properties: {
        cloudSourcePath: {
          type: "string",
          description: "Logical directory, folder ID, or file link representing the exact backup to download.",
        },
        localDestinationDir: {
          type: "string",
          description: "Directory path where the downloaded backup should be placed on the local machine.",
        },
      },
      required: ["cloudSourcePath", "localDestinationDir"],
    },
  },
];
